/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DialogBase: typeof import('./src/components/Dialog/Base.vue')['default']
    DialogRecordConfirmDelete: typeof import('./src/components/Dialog/Record/ConfirmDelete.vue')['default']
    DialogRecordCreate: typeof import('./src/components/Dialog/Record/Create.vue')['default']
    DialogRecordUpdate: typeof import('./src/components/Dialog/Record/Update.vue')['default']
    IconDelete: typeof import('./src/components/Icon/delete.vue')['default']
    IconDisplay: typeof import('./src/components/Icon/display.vue')['default']
    IconEdit: typeof import('./src/components/Icon/edit.vue')['default']
    IconHidden: typeof import('./src/components/Icon/hidden.vue')['default']
    IconPlus: typeof import('./src/components/Icon/plus.vue')['default']
    IconRefresh: typeof import('./src/components/Icon/refresh.vue')['default']
    IndicatorLoading: typeof import('./src/components/Indicator/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
